import { useState } from "react";
import { Link } from "react-router-dom";
import { cn, getStatusBg, getStatusLabel } from "../../lib/utils";
import {
  Clock,
  ArrowRight,
  Search,
  Filter,
  Train as TrainIcon,
  ShieldCheck,
  ExternalLink,
  SlidersHorizontal,
} from "lucide-react";

interface RecentPrediction {
  id?: string;
  trainNumber: string;
  trainName: string;
  station: string;
  predictedETA: string;
  delay?: number;
  predictedDelay?: number;
  confidence?: number;
  confidenceScore?: number;
  status: string;
  loco?: string;
  date?: string;
}

interface RecentPredictionsProps {
  predictions: RecentPrediction[];
  isLoading?: boolean;
}

export default function RecentPredictions({ predictions, isLoading }: RecentPredictionsProps) {
  const [filter, setFilter] = useState<"all" | "delayed" | "on-time">("all");
  const [search, setSearch] = useState("");

  const filteredPredictions = predictions.filter((pred) => {
    const delayVal = pred.predictedDelay ?? pred.delay ?? 0;
    const matchesFilter =
      filter === "all"
        ? true
        : filter === "delayed"
        ? delayVal > 15
        : delayVal <= 15;

    const matchesSearch =
      search === "" ||
      pred.trainNumber.toLowerCase().includes(search.toLowerCase()) ||
      pred.trainName.toLowerCase().includes(search.toLowerCase()) ||
      (pred.station && pred.station.toLowerCase().includes(search.toLowerCase()));

    return matchesFilter && matchesSearch;
  });

  return (
    <div className="nr-card overflow-hidden">
      {/* Header & Controls */}
      <div className="px-4 py-3.5 border-b border-[var(--nr-border)] flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-md bg-[var(--nr-surface-raised)] border border-[var(--nr-border)] flex items-center justify-center shrink-0 text-[var(--nr-accent)]">
            <Clock className="w-3.5 h-3.5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-[13px] font-semibold text-[var(--nr-text)] tracking-tight">
                Live Prediction Audit Feed
              </h2>
              <span className="text-[10px] font-mono px-1.5 py-0.2 rounded bg-[var(--nr-surface-raised)] text-[var(--nr-text-muted)] border border-[var(--nr-border)]">
                {predictions.length} Total
              </span>
            </div>
            <p className="text-[11px] text-[var(--nr-text-muted)]">
              Real-time ETA inferences generated by LightGBM model pipeline
            </p>
          </div>
        </div>

        {/* Filter and Search */}
        <div className="flex items-center gap-2 flex-wrap">
          <div className="relative">
            <Search className="w-3.5 h-3.5 text-[var(--nr-text-muted)] absolute left-2.5 top-2.5" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Filter by train # or station..."
              className="bg-[var(--nr-bg-subtle)] border border-[var(--nr-border)] rounded-md pl-8 pr-3 py-1.5 text-[11px] text-[var(--nr-text)] placeholder:text-[var(--nr-text-faint)] outline-none focus:border-[var(--nr-accent)] transition-colors w-44 font-mono"
            />
          </div>

          <div className="bg-[var(--nr-bg-subtle)] p-0.5 rounded-md border border-[var(--nr-border)] flex items-center gap-0.5">
            {[
              { key: "all", label: "All" },
              { key: "on-time", label: "On Time" },
              { key: "delayed", label: "Delayed" },
            ].map((btn) => (
              <button
                key={btn.key}
                onClick={() => setFilter(btn.key as any)}
                className={cn(
                  "px-2 py-1 rounded text-[11px] font-medium transition-colors",
                  filter === btn.key
                    ? "bg-[var(--nr-surface-raised)] text-[var(--nr-text)] border border-[var(--nr-border-strong)]"
                    : "text-[var(--nr-text-muted)] hover:text-[var(--nr-text-secondary)]"
                )}
              >
                {btn.label}
              </button>
            ))}
          </div>

          <Link
            to="/history"
            className="flex items-center gap-1 text-[11px] text-[var(--nr-accent)] hover:underline ml-1 font-medium"
          >
            Full Audit <ArrowRight className="w-3 h-3" />
          </Link>
        </div>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full text-left text-[12px] border-collapse">
          <thead>
            <tr className="border-b border-[var(--nr-border)] bg-[var(--nr-surface-raised)]/40 text-[var(--nr-text-muted)] font-medium text-[11px]">
              <th className="px-4 py-2.5">Train Details</th>
              <th className="px-4 py-2.5">Sector / Station</th>
              <th className="px-4 py-2.5">Predicted ETA</th>
              <th className="px-4 py-2.5">Expected Delay</th>
              <th className="px-4 py-2.5">Model Confidence</th>
              <th className="px-4 py-2.5">Operational Status</th>
              <th className="px-4 py-2.5 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[var(--nr-border)]/50">
            {isLoading ? (
              [...Array(5)].map((_, i) => (
                <tr key={i} className="animate-pulse">
                  <td colSpan={7} className="px-4 py-3">
                    <div className="h-4 bg-[var(--nr-surface-raised)] rounded w-full" />
                  </td>
                </tr>
              ))
            ) : filteredPredictions.length === 0 ? (
              <tr>
                <td colSpan={7} className="px-4 py-10 text-center">
                  <div className="flex flex-col items-center justify-center">
                    <div className="w-9 h-9 rounded-md bg-[var(--nr-surface-raised)] border border-[var(--nr-border)] flex items-center justify-center text-[var(--nr-text-muted)] mb-2">
                      <Filter className="w-4 h-4" />
                    </div>
                    <p className="text-[12px] font-medium text-[var(--nr-text)]">No predictions match criteria</p>
                    <p className="text-[11px] text-[var(--nr-text-muted)] mt-0.5">
                      Try clearing search filters or search a train in the ETA Predictor
                    </p>
                  </div>
                </td>
              </tr>
            ) : (
              filteredPredictions.map((pred, i) => {
                const delayVal = pred.predictedDelay ?? pred.delay;
                const confVal = pred.confidenceScore ?? pred.confidence;
                const stationVal = pred.station || "En Route";
                const statusVal =
                  pred.status ||
                  (delayVal != null
                    ? delayVal === 0
                      ? "on-time"
                      : delayVal <= 15
                      ? "slight-delay"
                      : delayVal <= 60
                      ? "delayed"
                      : "severe-delay"
                    : null);

                return (
                  <tr
                    key={pred.id || `${pred.trainNumber}-${i}`}
                    className="hover:bg-[var(--nr-surface-raised)]/50 transition-colors group"
                  >
                    {/* Train Info */}
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-2.5">
                        <div className="w-6 h-6 rounded bg-[var(--nr-surface-raised)] border border-[var(--nr-border)] flex items-center justify-center text-[var(--nr-text-muted)] shrink-0">
                          <TrainIcon className="w-3 h-3" />
                        </div>
                        <div>
                          <div className="flex items-center gap-1.5 font-mono">
                            <span className="font-bold text-[var(--nr-accent)] hover:underline cursor-pointer">
                              #{pred.trainNumber}
                            </span>
                            <span className="text-[10px] px-1 py-0.2 rounded bg-[var(--nr-surface-raised)] text-[var(--nr-text-muted)] border border-[var(--nr-border)]">
                              {pred.loco || "Express"}
                            </span>
                          </div>
                          <div className="text-[11px] text-[var(--nr-text)] font-medium truncate max-w-[180px]">
                            {pred.trainName}
                          </div>
                        </div>
                      </div>
                    </td>

                    {/* Sector / Station */}
                    <td className="px-4 py-3">
                      <div className="font-mono text-[11px] text-[var(--nr-text)] font-medium">
                        {stationVal}
                      </div>
                      <div className="text-[10px] text-[var(--nr-text-muted)]">
                        Track Section Active
                      </div>
                    </td>

                    {/* Predicted ETA */}
                    <td className="px-4 py-3">
                      <div className="font-mono text-[12px] font-semibold text-[var(--nr-text)] flex items-center gap-1">
                        <Clock className="w-3 h-3 text-[var(--nr-accent)]" />
                        {pred.predictedETA}
                      </div>
                      <div className="text-[10px] text-[var(--nr-text-muted)] font-mono">
                        {pred.date || "Today"}
                      </div>
                    </td>

                    {/* Delay */}
                    <td className="px-4 py-3 font-mono">
                      <span
                        className={cn(
                          "inline-flex items-center px-2 py-0.5 rounded text-[11px] font-semibold border",
                          delayVal == null
                            ? "bg-zinc-800 text-zinc-400 border-zinc-700"
                            : delayVal === 0
                            ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                            : delayVal <= 15
                            ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
                            : "bg-rose-500/10 text-rose-400 border-rose-500/20"
                        )}
                      >
                        {delayVal == null
                          ? "—"
                          : delayVal === 0
                          ? "On Time"
                          : `+${delayVal} min`}
                      </span>
                    </td>

                    {/* Model Confidence */}
                    <td className="px-4 py-3">
                      <div className="space-y-1 w-28">
                        <div className="flex items-center justify-between text-[10px] font-mono">
                          <span className="text-[var(--nr-text-muted)]">ML Score</span>
                          <span
                            className={cn(
                              "font-semibold",
                              confVal != null && confVal >= 85
                                ? "text-emerald-400"
                                : confVal != null && confVal >= 70
                                ? "text-amber-400"
                                : "text-rose-400"
                            )}
                          >
                            {confVal != null ? `${Number(confVal).toFixed(1)}%` : "—"}
                          </span>
                        </div>
                        <div className="h-1 rounded-full bg-[var(--nr-border)] overflow-hidden">
                          <div
                            className={cn(
                              "h-full rounded-full transition-all duration-300",
                              confVal != null && confVal >= 85
                                ? "bg-emerald-500"
                                : confVal != null && confVal >= 70
                                ? "bg-amber-500"
                                : "bg-rose-500"
                            )}
                            style={{ width: `${confVal ?? 0}%` }}
                          />
                        </div>
                      </div>
                    </td>

                    {/* Operational Status */}
                    <td className="px-4 py-3">
                      <span
                        className={cn(
                          "inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-medium border capitalize",
                          statusVal && statusVal !== "—"
                            ? getStatusBg(statusVal)
                            : "bg-zinc-800 text-zinc-400 border-zinc-700"
                        )}
                      >
                        <span className="w-1.5 h-1.5 rounded-full bg-current" />
                        {statusVal && statusVal !== "—" ? getStatusLabel(statusVal) : "Active"}
                      </span>
                    </td>

                    {/* Actions */}
                    <td className="px-4 py-3 text-right">
                      <div className="flex items-center justify-end gap-1.5 opacity-80 group-hover:opacity-100 transition-opacity">
                        <Link
                          to={`/search`}
                          title="Inspect Telemetry in ETA Predictor"
                          className="p-1 rounded bg-[var(--nr-surface-raised)] hover:bg-[var(--nr-border)] text-[var(--nr-text-secondary)] hover:text-[var(--nr-text)] border border-[var(--nr-border)] transition-colors"
                        >
                          <ExternalLink className="w-3 h-3" />
                        </Link>
                        <Link
                          to={`/simulate`}
                          title="Simulate Scenario What-If"
                          className="p-1 rounded bg-[var(--nr-surface-raised)] hover:bg-[var(--nr-border)] text-[var(--nr-text-secondary)] hover:text-[var(--nr-accent)] border border-[var(--nr-border)] transition-colors"
                        >
                          <SlidersHorizontal className="w-3 h-3" />
                        </Link>
                      </div>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

      {/* Footer Audit Bar */}
      <div className="px-4 py-2 border-t border-[var(--nr-border)] bg-[var(--nr-bg-subtle)]/40 flex items-center justify-between text-[11px] text-[var(--nr-text-muted)]">
        <div className="flex items-center gap-1.5">
          <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
          <span>Cryptographically validated inference logs • Railway Operational Safety Tier-1</span>
        </div>
        <span className="font-mono text-[10px]">Showing top {filteredPredictions.length} audit entries</span>
      </div>
    </div>
  );
}
