from pydantic import BaseModel, Field
from typing import Dict, Any

class ServiceTestResponse(BaseModel):
    """
    Temporary schema used to validate and return the request configuration generated by the services.
    """
    url: str = Field(..., description="The generated external API URL")
    params: Dict[str, Any] = Field(..., description="The query parameters to be sent with the request")
    headers: Dict[str, str] = Field(..., description="The HTTP headers to be sent with the request")
